### PR TITLE
population density data

### PR DESCRIPTION
**Pull request by emackev**
Adding population density data

### CODE REVIEW

**Comment by emackev** [comment]
@Niklewa , I get this error when I run cleaning_pipeline.py, related to clean_poverty (a file I haven't changed). Any ideas what is going on? 

image

**Comment by rfl-urbaniak** [comment]
this screen shot does not contain the error message.  Asked @Niklewa to take a look and try to fix.

**Comment by Niklewa** [comment]
I believe that the target branch should be staging-county-data. The problem is that this PR uses unrefactored code in some places for some reason. I will change the target and pull from origin staging-county-data. edit: This fixed the problem with the cleaning_pipeline

A different issue has arisen, there is an 'Unnamed: 0' value in the year column, which was identified by a test. I will work on that now.

**Comment by Niklewa** [comment]
I dealt with the mentioned issue. The problem was that the raw file was stored with the index column.

test_slim returns:
ValueError: No tau samples found. Run generate_tensed_samples first.

It signifies a missing trained model, which does not block merging.

**Review by Niklewa — APPROVED** [review]

**Pull request merged**
