### PR TITLE
adding basic variables at MSA level

### PR DESCRIPTION
**Pull request by Niklewa**

### CODE REVIEW

**Review by rfl-urbaniak — CHANGES_REQUESTED** [review]
- refactor `save_file` to avoid redundancies
- make sure you test the new cleanup pipeline also for the county level and add a test that does so automatically
- revise the structure of the data_gude (walkability/road density should be in transportation)
- add TOC to the data guide as it is growing a bit large

**Comment by Niklewa** [comment]
> * refactor `save_file` to avoid redundancies
> 
>     * make sure you test the new cleanup pipeline also for the county level and add a test that does so automatically
> 
>     * revise the structure of the data_gude (walkability/road density should be in transportation)
> 
>     * add TOC to the data guide as it is growing a bit large

I have implemented all the corrections. The tests have been created in a separate PR.

**Review by rfl-urbaniak — CHANGES_REQUESTED** [review]
general data rules is now a supersection of everything in the data guide as far as the TOC is involved, make sure it's on the same level as the other ones. Also, I'm pretty sure we have more outcome variables, something is off. basically, any variable that comes as a time series is an outcome variable if it's not an intervention variable. Can you fix the categorization in the TOC?

**Comment by rfl-urbaniak** [comment]
Also, please make sure that all variables that `list_avaiable_features` spits out are accounted for. :)

**Comment by Niklewa** [comment]
> general data rules is now a supersection of everything in the data guide as far as the TOC is involved, make sure it's on the same level as the other ones. Also, I'm pretty sure we have more outcome variables, something is off. basically, any variable that comes as a time series is an outcome variable if it's not an intervention variable. Can you fix the categorization in the TOC?

Done

**Comment by rfl-urbaniak** [comment]
Screenshot from 2024-01-11 15-24-41

**Review by rfl-urbaniak — CHANGES_REQUESTED** [review]
fails make test fails make lint

**Comment by Niklewa** [comment]
> fails make test fails make lint

Made adjustments, now everything works.

**Review by rfl-urbaniak — APPROVED** [review]

**Pull request merged**
